### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sabyadg** [soedinglab/merlot#10]
When I tried to install it from source as,
install.packages("~/Downloads/merlot-master.zip", type="source", repos = NULL)
gives error:
and  if I try,
install.packages("~/Downloads/merlot-master.zip",repos = NULL, type = "source" type="binary")
Gives error as,
Warning in install.packages :
  installation of package ‘/Users/admin/Downloads/merlot-master.zip’ had non-zero exit status

Gives error as well,
Warning in install.packages :
  package ‘~/Downloads/merlot-master.zip’ is not available (as a binary package for R version 3.5.1)

**Comment by galicae** [comment]
Hello and thank you for trying out MERLoT! It would help us figure the problem out if you could provide us with more details. There should be an error message in the R console output; this would be very helpful. Also, what is your OS? Did you try the github installation?

**Comment by galicae** [comment]
I will go ahead and close this issue. Please feel free to re-open if the problems persist!
