### ISSUE TITLE
Merlot installation: csgraph_mod and shortest_path_mod

### ISSUE THREAD

**Issue by laurahum** [soedinglab/merlot#6]
Hi Gonzalo,

I tried to install Merlot in my windows computer and I encountered trouble when importing 'csgraph_mod' and 'shortest_path_mod' in python (anaconda). I think that the problem with these libraries was previously pointed out by Christian. It would be very helpful if you could give me some feedback on the issue so I can do a further trial of Merlot. 

On a minor note, there is a typo on the following line of README.md, where **type** should not be between quotation marks:
install.packages("/url_in_your_computer/merlot_0.1.0.tar.gz", "types"="source", repos = NULL)

Best,
Laura

**Comment by gonzaparra** [comment]
Hi Laura,

try to install it from here:
https://github.com/soedinglab/csgraph_mod/

Let me know if you can make it.

Best,

Gonza

-----
R. Gonzalo Parra, PhD
EMBO Postdoctoral Fellow
Quantitative and Computational Biology Group
http://www.mpibpc.mpg.de/de/soeding
Max Planck Institute for Biophysical Chemistry
Am Fassberg 11
37077, Göttingen, Germany

2017-08-02 10:02 GMT+02:00 laurahum <notifications@github.com>:
